version: "3"

services:
  app:
    build: images/nginx
    env_file: env/docker.env
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    build: images/php/${PHP_VERSION}
    env_file: env/docker.env
    links:
      - db
    volumes: *appvolumes
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: percona:5.7
    command: --max_allowed_packet=64M
    ports:
      - "3306:3306"
    env_file: 
      - env/db.env
      - env/docker.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:5.0-alpine

  elasticsearch:
    image: markoshust/magento-elasticsearch:7.16
    env_file: env/docker.env
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  phpmyadmin:
    build: images/phpmyadmin
    env_file:
      - env/db.env
      - env/docker.env
    ports:
      - 8080:80

volumes:
  appdata:
  dbdata:
  sockdata:
  ssldata:
